### ISSUE TITLE
Chinese (ZH) wikipedia not working

### ISSUE THREAD

**Issue by TMavica** [mkiol/Zimpedia#13]
After searching, it opens the link with ?????.html

**Comment by mkiol** [comment]
Thanks for the report. I'm working on a fix,

Did you use "wikipedia_zh_all_nopic.zim" form kwix site? Did you have any problem with opening this file? When I click on "wikipedia_zh_all_nopic.zim" on "Choose ZIM file", app shows following error on console: "Value too large for defined data type"..

**Comment by TMavica** [comment]
I use ZH all, if i search with English, it is fine. but chinese not

**Comment by TMavica** [comment]
yes. i use file from kwix, and no problem opening it
Just ifni search with chinese char, it show the result, but after click it, it opens browser, the link said .......??????.html

**Comment by mkiol** [comment]
So, I was testing it for few hours and I don't see any issue. I can search using chinese characters and also I don't have any problem with opening URLs. Everything seems to work fine!

There was some issue with not-Latin characters, but this issue was solved in **1.0-5** version. What version do you have installed?

**Comment by TMavica** [comment]
1.05

I using wikipedia zh non index, 7.4GB one
When I search with 蘋果, the url opened with http://localhost:9091/A/??.html
When I search with 銅鑼灣,  the url opened with http://localhost:9091/A/???.html

so the "?" is mean the chinese char, 3 ? = 3 chinese char, 2 ? = 2 chinese char
If I manual change ?? to 蘋果, ??? to 銅鑼灣, the browser can open that wiki content

**Comment by mkiol** [comment]
I am still trying to reproduce the issue you are observing. Unfortunately, no success so far :-(

The ZIM file with pics is way to large for my SD card, so I'm doing tests with [nopic ZIM](http://download.kiwix.org/zim/wikipedia_zh_all_nopic.zim) version. Please check if issue is the same with this file as well.

Additionally, [here](https://github.com/mkiol/Zimpedia/tree/master/sailfish/binaries) is rpm with debugging information. Please install this version. When you run app from terminal, please grab everything and send to me. 

If you need any help installing rpm or running app from terminal, please let me know.

**Comment by TMavica** [comment]
Here is the log 

https://db.tt/cmbPXoDv

**Comment by mkiol** [comment]
Thanks! In case something comes up, I'll let you know.

**Comment by TMavica** [comment]
Good to see you found have problem in it

**Comment by mkiol** [comment]
Unfortunately, I still haven't managed to reproduce the issue on my phone. Sorry :-(

After reading your log file, I see that there is a problem in passing URLs to Zimpedia server. Instead `/A/%E8%98%8B%E6%9E%9C.html` server receives `/A/`, but honestly I have no idea why.

Which SailfishOS version is installed on your phone? Is your default system browser is sailfish-browser?

**Comment by TMavica** [comment]
Yes. Default is sailfish browser

**Comment by TMavica** [comment]
2.01

**Comment by TMavica** [comment]
I solved now
It is because I use English language of Jolla, if i change to Chinese (Hong Kong), I can open the link without ????.html

**Comment by mkiol** [comment]
Super! I am glad to hear that :-)
