### ISSUE TITLE
I can't open Zimpedia file in my Jolla Tablet 

### ISSUE THREAD

**Issue by carmenfdezb** [mkiol/Zimpedia#15]
I use Zimpedia in my phone without problems (I can open 11.16 Gb zim file from my sdcard). However, if I put this sdcard in my Jolla Tablet and open Zimpedia app, I can select the zim file but nothing is happend.

If I open zimpedia on terminal, I get the following output:

[nemo@Jolla ~]$ harbour-zimpedia
[D] QWaylandEglClientBufferIntegration::QWaylandEglClientBufferIntegration:62 - Using Wayland-EGL
[W] ZimServer::loadZimFile:85 - Unable to open ZIM file "/media/sdcard/ee635fc8-8b15-48c0-8c30-50606c3
af071/Wikipedia/wikipedia_es_all_2015-11.zim" !
[W] ZimServer::loadZimFile:86 - Details: error 11 seeking to end in file /media/sdcard/ee635fc8-8b15-4
8c0-8c30-50606c3af071/Wikipedia/wikipedia_es_all_2015-11.zim: Recurso no disponible temporalmente

**Comment by mkiol** [comment]
Thank you for the report. I can confirm this issue. The good news is that I know how to fix it :-)

**Comment by carmenfdezb** [comment]
Excellent!! Thank you so much!!

**Comment by mkiol** [comment]
I've just uploaded to [OpenRepos](https://openrepos.net/content/mkiol/zimpedia) a new package: 1.1-0. Please let me know if that fixes the issue.

**Comment by carmenfdezb** [comment]
Yeah!!! It works perfect!! Thank you!!
