### ISSUE TITLE
FeatureRequest: Improve Zimpedia

### ISSUE THREAD

**Issue by ghost** [mkiol/Zimpedia#25]
Hi mkiol 
i like zimpedia a lot, so i want to know if is there are plans to improve this wonderful app?
i wish zimpedia more powerful on renderer and without webview,
i will contribute with 50EU : )
thanks

**Comment by mkiol** [comment]
I'm really glad you find Zimpedia useful :-)

Actually, I'm planing a new release but it will be very tiny release. Only libzim version will be updated (1.4=>4.0.4) to support newer ZIM format. 

You are not a fan of WebView, right? I know it is extremely slow and laggy on XperiaX but I'm afraid nothing can be done right now. We have to wait for Qt update to version 5.6 and QWebEngine.

**Comment by ghost** [comment]
@mkiol i do not like webview because it feel online work, i like pure offline work.  i liked the app harbour-wunderfitz a dictionary offline i am not sure if that app is using webview, but it is not looking or feeling webview. 
thanks for all the development to the fishOS . :  )

**Comment by carlosgonz0** [comment]
Hi @mkiol 
nice release/work! 
any way to donation at zimpedia/jupii?

**Comment by carlosgonz0** [comment]
I do not know how use full-text search? on the fresh release. can you explain me.

**Comment by mkiol** [comment]
As to the Full-text search, so:
1. You need to have a ZIM file that contains full-text index. Most recent wikipedia dumps should have it. You can check it in Zimpedia on Details page (=> check "Full-text index" property). Details page can be opened by clicking on "Show details" on ZIM file item context menu.
2. You have to change search mode setting to "Full-text" (Settings page)

If 1. and 2. is done when you enter a text in the search field, Zimpedia will list articles that contain searched phase in their text body. By title search lists only articles that contain searched phase in the title.

Full-text search is something that was introduced in the latest LibZIM version.

@GNUuser 
Regarding donations, so I would be very grateful for positive comment on OpenRepos or/and Jolla store. Actually it is very rewarding to see that your work is useful. But.. if you really want to spend some of your money, I recommend small donation to OpenZIM or Wikipedia. Zimpedia wouldn't be possible without these projects.

**Comment by carlosgonz0** [comment]
ok  i got it now, nice feature!. what about  in futures releases features like TTS?

**Comment by mkiol** [comment]
> what about in futures releases features like TTS

I will think about it :-)

**Comment by carlosgonz0** [comment]
hi, Michal
 can you close this PR? i can not close it a.t.m.
i am fine with the big improvement of v2.2.1.
the  issues with webview is too slow, bad render, online feeling :  |

**Comment by carlosgonz0** [comment]
i having  some issues with inverted-ambiences.

**Comment by mkiol** [comment]
Fixed in  f29e47a
