### ISSUE TITLE
Problem opening big zimfiles

### ISSUE THREAD

**Issue by seiichiro0185** [mkiol/Zimpedia#3]
Hi,

thanks for your effort creating zimpedia! I found an issue with opening big files (German wikipedia, about 4.2GB in my case). I can select the file, but nothing happens. On the terminal I get the following output:

[D] QWaylandEglClientBufferIntegration::QWaylandEglClientBu
fferIntegration:62 - Using Wayland-EGL
[D] main:53 - "Couldn't load translation for locale C from
/usr/share/harbour-zimpedia/translations"
[W] ZimServer::loadZimFile:74 - Unable to open ZIM file "/h
ome/nemo/wikipedia/wikipedia_de_all_nopic_2015-11.zim" !
[W] ZimServer::loadZimFile:75 - Details: error 75 seeking t
o end in file /home/nemo/wikipedia/wikipedia_de_all_nopic_2
015-11.zim: Value too large for defined data type

So it seems there is some problem with to small variable types in the zimfile reading code.

**Comment by mkiol** [comment]
Thank you for reporting this. I've just uploaded to OpenRepos new version (1.0-2) with a fix for that.

**Comment by seiichiro0185** [comment]
Thanks a lot for the really quick fix. It's working as expected now.
