### ISSUE TITLE
FeatureRequest: Ubuntu Touch

### ISSUE THREAD

**Issue by carlosgonz0** [mkiol/Zimpedia#30]
Hi mkiol
it is posible to port this good app to ubuntu touch?

**Comment by kelson42** [comment]
@GNUuser Sorry to hijack a bit here the discussion, but Kiwix provides a port for Ubuntu Touch https://uappexplorer.com/app/kiwix

**Comment by carlosgonz0** [comment]
> @GNUuser Sorry to hijack a bit here the discussion, but Kiwix provides a port for Ubuntu Touch https://uappexplorer.com/app/kiwix

Thanks you.

**Comment by carlosgonz0** [comment]
> @GNUuser Sorry to hijack a bit here the discussion, but Kiwix provides a port for Ubuntu Touch https://uappexplorer.com/app/kiwix

It is possible to fully translate kiwix port?  it look a lot diferent at zimpedia.

**Comment by kelson42** [comment]
So far its not, but there is a ticket about it here https://github.com/kiwix/kiwix-js/issues/13. Maybe if you put a comment again this would help to raise-up the topic on the top of the pile again?
